name: Build & Deploy Live

on:
  push:
    branches: live
  pull_request:
    branches: live

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      # Install composer dependencies
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      # Install npm dependencies & build
      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      # Cleanup
      - name: Delete unnecessary files
        run: |
          rm -r node_modules
          rm -r .git
          rm -r .github
          rm -r .parcel-cache
          rm -r .gitignore
          rm -r .editorconfig
          rm -r .vscode
          rm -r .claude
          rm -r package-lock.json
          rm -r package.json
          rm -r composer.json
          rm -r composer.lock
          rm -r readme.md

      # SFTP Deploy
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.ftp_server_live }}
          username: ${{ secrets.ftp_user_live }}
          password: ${{ secrets.ftp_password_live }}
          server-dir: ${{ secrets.ftp_path_live }}
          protocol: sftp
          port: 22
